### ISSUE TITLE
[BE] 배포, CI/CD 설정

### ISSUE THREAD

**Issue by Choi-chunsam** [KangHayeonn/together-party-tonight-server#7]
- [x] aws ec2, rds, s3 만들기
- [x] aws ec2에 rds, s3 연동하기
- [x] aws IAM 백엔드 전용 사용자 만들어서 팀원에게 공유하기
- [x] ec2에 java, mysql, redis설치하기
- [x] gitflows에 ci/cd를 위한 설정파일 만들기
- [x] ci/cd에 필요한 설정파일 만들고 ec2인스턴스에 프로젝트 올라가는지 테스트하기
- [x] 민감정보가 포함된 yml파일들을 깃허브에 올리지않고 aws에 따로 올려서 실제 서버 실행되는지 확인하기

**Comment by KangHayeonn** [comment]
완료
